### ISSUE TITLE
win有编译好的最新版的包吗？

### ISSUE THREAD

**Issue by zhaoliang0302** [wangbjun/catya#5]
自己不会编译，最新版的没有编译好的windows版本

**Comment by wangbjun** [comment]
没的了，你看看这个图形库官网有教程的发自我的 iPhone在 2023年11月26日，14:50，Xiangjiao ***@***.***> 写道：﻿
自己不会编译，最新版的没有编译好的windows版本

**Comment by zhaoliang0302** [comment]
我自己尝试了下，但是没有编程基础，搞不定编译，能帮忙编译个win的exe文件吗，感谢
